#docker compose of a server apache instance

version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: apache-server
    ports:
    - '80:80'
    volumes:
    - .:/usr/local/apache2/htdocs